[package]
name = "chain-evm"
version = "0.1.0"
edition = "2018"

[dependencies]
evm = "0.33.0"
imhamt = { path = "../imhamt" }
primitive-types = "0.10.1"
aurora-engine-precompiles = { path = "../../aurora-engine/engine-precompiles" }

[dev-dependencies]
proptest = "1.0.0"
test-strategy = "0.1"
